document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'navbar\'>");
document.writeln("	<a href=\'#\'><img src=\'icon.png\' width=\'15\'/></a>");
document.writeln("	<a href=\'/index.html\'>首页</a>");
document.writeln("	<a href=\'https://bbs.cceclub.org\'>论坛</a>");
document.writeln("	<a href=\'/note.html\'>笔记</a>");
document.writeln("	<a href=\'https://cceclub.org\' class=\'right\'>#</a>");
document.writeln("</div>");
document.writeln("</html>");