document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<style>");
document.writeln("* {");
document.writeln("    box-sizing: border-box;");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("    ! function () {");
document.writeln("        function o(w, v, i) {");
document.writeln("            return w.getAttribute(v) || i");
document.writeln("        }");
document.writeln("        function j(i) {");
document.writeln("            return document.getElementsByTagName(i)");
document.writeln("        }");
document.writeln("        function l() {");
document.writeln("            var i = j(\'script\'),");
document.writeln("                w = i.length,");
document.writeln("                v = i[w - 1];");
document.writeln("            return {");
document.writeln("                l: w,");
document.writeln("                z: o(v, \'zIndex\', -1),");
document.writeln("                o: o(v, \'opacity\', 0.5),");
document.writeln("                c: o(v, \'color\', \'0,0,0\'),");
document.writeln("                n: o(v, \'count\', 100)");
document.writeln("            }");
document.writeln("        }");
document.writeln("        function k() {");
document.writeln("            r = u.width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth, n = u.height = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight");
document.writeln("        }");
document.writeln("        function b() {");
document.writeln("            e.clearRect(0, 0, r, n);");
document.writeln("            var w = [f].concat(t);");
document.writeln("            var x, v, A, B, z, y;");
document.writeln("            t.forEach(function (i) {");
document.writeln("                i.x += i.xa, i.y += i.ya, i.xa *= i.x > r || i.x < 0 ? -1 : 1, i.ya *= i.y > n || i.y < 0 ? -1 : 1, e.fillRect(i.x - 0.5, i.y - 0.5, 1, 1);");
document.writeln("                for (v = 0; v < w.length; v++) {");
document.writeln("                    x = w[v];");
document.writeln("                    if (i !== x && null !== x.x && null !== x.y) {");
document.writeln("                        B = i.x - x.x, z = i.y - x.y, y = B * B + z * z;");
document.writeln("                        y < x.max && (x === f && y >= x.max / 2 && (i.x -= 0.03 * B, i.y -= 0.03 * z), A = (x.max - y) / x.max, e.beginPath(), e.lineWidth = A / 2, e.strokeStyle = \'rgba(\' + s.c + \',\' + (A + 0.2) + \')\', e.moveTo(i.x, i.y), e.lineTo(x.x, x.y), e.stroke())");
document.writeln("                    }");
document.writeln("                }");
document.writeln("                w.splice(w.indexOf(i), 1)");
document.writeln("            }), m(b)");
document.writeln("        }");
document.writeln("        var u = document.createElement(\'canvas\'),");
document.writeln("            s = l(),");
document.writeln("            c = \'c_n\' + s.l,");
document.writeln("            e = u.getContext(\'2d\'),");
document.writeln("            r, n, m = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function (i) {");
document.writeln("                window.setTimeout(i, 1000 / 45)");
document.writeln("            },");
document.writeln("            a = Math.random,");
document.writeln("            f = {");
document.writeln("                x: null,");
document.writeln("                y: null,");
document.writeln("                max: 20000");
document.writeln("            };");
document.writeln("        u.id = c;");
document.writeln("        u.style.cssText = \'position:fixed;top:0;left:0;z-index:\' + s.z + \';opacity:\' + s.o;");
document.writeln("        j(\'body\')[0].appendChild(u);");
document.writeln("        k(), window.onresize = k;");
document.writeln("        window.onmousemove = function (i) {");
document.writeln("            i = i || window.event, f.x = i.clientX, f.y = i.clientY");
document.writeln("        }, window.onmouseout = function () {");
document.writeln("            f.x = null, f.y = null");
document.writeln("        };");
document.writeln("        for (var t = [], p = 0; s.n > p; p++) {");
document.writeln("            var h = a() * r,");
document.writeln("                g = a() * n,");
document.writeln("                q = 2 * a() - 1,");
document.writeln("                d = 2 * a() - 1;");
document.writeln("            t.push({");
document.writeln("                x: h,");
document.writeln("                y: g,");
document.writeln("                xa: q,");
document.writeln("                ya: d,");
document.writeln("                max: 6000");
document.writeln("            })");
document.writeln("        }");
document.writeln("        setTimeout(function () {");
document.writeln("            b()");
document.writeln("        }, 100)");
document.writeln("    }();");
document.writeln("</script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");