document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'sidebar\'>");
document.writeln("	    <div class=\'side\'>");
document.writeln("		<h3>关于本站</h3>");
document.writeln("		<p style=\'text-align:center;\'><img src=\'icon.png\' width=\'85\'/></p>");
document.writeln("		<p style=\'text-align:center;\'>一个收录优质网站的导航Page");
document.writeln("		<br/>简单、简约");
document.writeln("		<br/>David Lee先森的自由Page</p>");
document.writeln("		</div>");
document.writeln("		<div class=\'side\'>");
document.writeln("		<h3>捐助本站</h3>");
document.writeln("		<p style=\'text-align:center;\'>此网站为出于兴趣所作<br/>非营利网站</p>");
document.writeln("		</div>");
document.writeln("		<div class=\'side\'>");
document.writeln("		<h3>联系方式</h3>");
document.writeln("		<p style=\'text-align:center;\'>暂不开放</p>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</html>");